spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

resilience4j:
  circuitbreaker:
    instances:
      userService:
        # Size of the sliding window
        #Circuit breaker remembers only the last 5 calls.
        slidingWindowSize: 5
        # Minimum calls before calculating failure rate
         #Circuit breaker will not calculate failure rate until 2 calls are made.
        minimumNumberOfCalls: 2
        # Failure rate threshold in percentage to open circuit
        #If 50% or more calls in the window fail → circuit OPENS.
        failureRateThreshold: 50
        # Duration the circuit remains OPEN before transitioning to HALF_OPEN
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        
