spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8886

server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 50
