spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 50
